# pseudo Makefile for the Haskell Report
#
#   Please read the README file first
#
doIt: warn
	make -f makefile.real \
	&& make -f makefile.real \
	&& make -f makefile.real

warn:
	echo "I hope you have \"makeindex\";"
	echo "If not, follow the instructions in README"
